spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false

  mail:
    host: ${SPRING_MAIL_HOST:mailhog}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_STARTTLS:false}
    default-encoding: UTF-8

  application:
    name: notification-service

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 9005

main:
  allow-bean-definition-overriding: true
